services:
    _defaults:
        public: false

    Oro\Bundle\UserBundle\Command\CreateUserCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\UserBundle\Command\ImpersonateUserCommand:
        arguments:
            - '@doctrine'
            - '@router'
            - '@oro_config.manager'
            - '@oro_user.manager'
            - '@oro_locale.formatter.date_time'
        tags:
            - { name: console.command }

    Oro\Bundle\UserBundle\Command\ListUserCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\UserBundle\Command\UpdateUserCommand:
        tags:
            - { name: console.command }
