services:
    oro_user.api.get.set_user_profile_entity_id:
        class: Oro\Bundle\UserBundle\Api\Processor\Get\SetUserProfileEntityId
        arguments:
            - '@security.token_storage'
        tags:
            - { name: oro.api.processor, action: get, group: normalize_input, class: Oro\Bundle\UserBundle\Api\Model\UserProfile }

    oro_user.api.create.save_user:
        class: Oro\Bundle\UserBundle\Api\Processor\Create\SaveUser
        arguments:
            - '@oro_user.manager'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\UserBundle\Entity\User }

    oro_user.api.customize_form_data.disable_user:
        class: Oro\Bundle\UserBundle\Api\Processor\DisableUserByDefault
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: post_submit, parentAction: create, class: Oro\Bundle\UserBundle\Entity\User, priority: 10 }
