entity_config:
    attachment:
        field:
            items:
                # indicates whether to use DAM to attachments loading
                use_dam:
                    options:
                        value_type: boolean
                        default_value: false
                        allowed_type: [file, image]
                        create_only: true
                    form:
                        type: Oro\Bundle\EntityConfigBundle\Form\Type\ChoiceType
                        options:
                            choices:
                                Yes: 1
                                No: 0
                            placeholder: false
                            block: general
                            subblock: properties
                            label: oro.digitalasset.entity_config.attachment.field.items.use_dam.label
                            tooltip: oro.digitalasset.entity_config.attachment.field.items.use_dam.tooltip
