services:
    oro_form.validator.constraint_factory:
        class: Oro\Bundle\FormBundle\Validator\ConstraintFactory

    oro_form.twig.form_extension:
        class: Oro\Bundle\FormBundle\Twig\FormExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        public: false
        tags:
            - { name: twig.extension }

    oro_form.model.update_handler:
        deprecated: The "%service_id%" service is deprecated since v2.1.0 use Oro\Bundle\FormBundle\Model\UpdateHandlerFacade (oro_form.update_handler) instead
        # This service marked as public for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true
        class: Oro\Bundle\FormBundle\Model\UpdateHandler
        arguments:
            - '@request_stack'
            - '@session'
            - '@oro_ui.router'
            - '@oro_entity.doctrine_helper'
            - '@oro_form.form.handler.default'

    Oro\Bundle\FormBundle\Model\UpdateHandler:
        alias: oro_form.model.update_handler

    oro_form.provider.html_tag_provider:
        class: Oro\Bundle\FormBundle\Provider\HtmlTagProvider
        arguments:
            - []
            - '%oro_form.html_purifier_mode%'
            - '%oro_form.html_purifier_iframe_domains%'
            - '%oro_form.html_purifier_uri_schemes%'

    oro_form.count_query_optimization_listener:
        class: Oro\Bundle\FormBundle\EventListener\CountQueryOptimizationListener
        tags:
            - { name: kernel.event_listener, event: oro.entity.count_query.optimize, method: onOptimize }

    oro_form.event.event_dispatcher:
        class: Oro\Bundle\FormBundle\Event\EventDispatcher
        arguments:
            - '@event_dispatcher'

    oro_form.doctrine.orm.validator_initializer:
        class: Oro\Bundle\FormBundle\Validator\DoctrineInitializer
        public: false
        decorates: doctrine.orm.validator_initializer
        arguments:
            - '@oro_form.doctrine.orm.validator_initializer.inner'

    oro_form.update_factory:
        class: Oro\Bundle\FormBundle\Model\UpdateFactory
        arguments:
            - '@form.factory'
            - '@oro_form.registry.form_handler'
            - '@oro_form.registry.form_template_data_provider'

    oro_form.update_handler:
        class: Oro\Bundle\FormBundle\Model\UpdateHandlerFacade
        # This service marked as public for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true
        arguments:
            - '@request_stack'
            - '@session'
            - '@oro_ui.router'
            - '@oro_entity.doctrine_helper'
            - '@oro_form.update_factory'

    Oro\Bundle\FormBundle\Model\UpdateHandlerFacade:
        alias: oro_form.update_handler

    oro_form.registry.form_template_data_provider:
        class: Oro\Bundle\FormBundle\Model\FormTemplateDataProviderRegistry
        public: false
        arguments:
            - ~ # providers. Set by Oro\Bundle\FormBundle\DependencyInjection\Compiler\FormTemplateDataProviderCompilerPass

    oro_form.provider.from_template_data.default:
        class: Oro\Bundle\FormBundle\Provider\FromTemplateDataProvider
        public: false
        tags:
            - { name: oro_form.form_template_data_provider, alias: default }

    oro_form.registry.form_handler:
        class: Oro\Bundle\FormBundle\Model\FormHandlerRegistry
        public: false
        arguments:
            - ~ # handlers. Set by Oro\Bundle\FormBundle\DependencyInjection\Compiler\FormHandlerCompilerPass

    oro_form.form.handler.default:
        class: Oro\Bundle\FormBundle\Form\Handler\FormHandler
        arguments:
            - '@oro_form.event.event_dispatcher'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_form.form.handler, alias: default }
