config:
    shim:
        'routing':
            exports: 'window.Routing'
    paths:
        'routing': 'bundles/fosjsrouting/js/router.js'
        'oronavigation/js/app/modules/navigation-module': 'bundles/oronavigation/js/app/modules/navigation-module.js'

    appmodules:
        - oronavigation/js/app/modules/navigation-module
