services:
    _defaults:
        public: false

    Oro\Bundle\ApiBundle\Command\CacheClearCommand:
        arguments:
            - '@oro_api.cache_manager'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DebugCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DocCacheClearCommand:
        arguments:
            - '@oro_api.cache_manager'
            - '%oro_api.api_doc.views%'
            - '%kernel.environment%'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpConfigCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpConfigReferenceCommand:
        arguments:
            - '@oro_api.config_extension_registry'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpMetadataCommand:
        tags:
            - { name: console.command }
