services:
    _defaults:
        public: false

    Oro\Bundle\ApiBundle\Command\CacheClearCommand:
        arguments:
            - '@oro_api.cache_manager'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DebugCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.action_processor_bag'
            - '@oro_api.processor_bag'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DocCacheClearCommand:
        arguments:
            - '@oro_api.cache_manager'
            - '%oro_api.api_doc.views%'
            - '%kernel.environment%'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.subresources_provider'
            - '@doctrine'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpConfigCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.processor_bag'
            - '@oro_api.config_provider'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpConfigReferenceCommand:
        arguments:
            - '@oro_api.config_extension_registry'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpMetadataCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.processor_bag'
            - '@oro_api.metadata_provider'
            - '@oro_api.config_provider'
        tags:
            - { name: console.command }
