services:
    Oro\Bundle\ApiBundle\Command\CacheClearCommand:
        arguments:
            - '@oro_api.cache_manager'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DebugCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.action_processor_bag'
            - '@oro_api.processor_bag'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DocCacheClearCommand:
        arguments:
            - '@oro_api.cache_manager'
            - '%oro_api.api_doc.views%'
            - '%kernel.environment%'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.subresources_provider'
            - '@oro_entity.entity_class_provider.orm'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpConfigCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.processor_bag'
            - '@oro_api.config_provider'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpConfigReferenceCommand:
        arguments:
            - '@oro_api.config_extension_registry'
        tags:
            - { name: console.command }

    Oro\Bundle\ApiBundle\Command\DumpMetadataCommand:
        arguments:
            - '@oro_api.value_normalizer'
            - '@oro_api.resources_provider'
            - '@oro_api.processor_bag'
            - '@oro_api.metadata_provider'
            - '@oro_api.config_provider'
        tags:
            - { name: console.command }

    oro_cms.command.api_doc_dump_service_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                - '@router'
                - '@nelmio_api_doc.formatter.simple_formatter'
                - '@nelmio_api_doc.formatter.markdown_formatter'
                - '@nelmio_api_doc.formatter.html_formatter'
                - '@nelmio_api_doc.extractor.api_doc_extractor'
        tags:
            - { name: container.service_locator }

    Oro\Bundle\ApiBundle\Command\ApiDocDumpCommand:
        arguments:
            - '@oro_cms.command.api_doc_dump_service_locator'
        tags:
            - { name: console.command, command: 'api:doc:dump' }

    oro_cms.command.api_swagger_dump_service_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                - '@nelmio_api_doc.extractor.api_doc_extractor'
                - '@nelmio_api_doc.formatter.swagger_formatter'
        tags:
            - { name: container.service_locator }

    Oro\Bundle\ApiBundle\Command\ApiSwaggerDumpCommand:
        arguments:
            - '@oro_cms.command.api_swagger_dump_service_locator'
        tags:
            - { name: console.command, command: 'api:swagger:dump' }
