services:
    oro_api.customize_form_data.handle_unidirectional_associations:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\HandleUnidirectionalAssociations
        arguments:
            - '@oro_api.form.unidirectional_association_handler'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: post_submit }
