services:
    Oro\Bundle\InstallerBundle\Command\CheckRequirementsCommand:
        public: false
        class: Oro\Bundle\InstallerBundle\Command\CheckRequirementsCommand
        tags:
            - { name: console.command }

    Oro\Bundle\InstallerBundle\Command\InstallCommand:
        public: false
        class: Oro\Bundle\InstallerBundle\Command\InstallCommand
        arguments:
            - '@oro_installer.yaml_persister'
            - '@oro_installer.script_manager'
            - '@doctrine'
            - '@event_dispatcher'
        tags:
            - { name: console.command }

    Oro\Bundle\InstallerBundle\Command\LoadPackageDemoDataCommand:
        public: false
        class: Oro\Bundle\InstallerBundle\Command\LoadPackageDemoDataCommand
        arguments:
            - '@kernel'
            - '@?oro_migration.data_fixtures.loader'
            - '@?oro_migration.data_fixtures.executor'
            - '@?oro_migration.locator.fixture_path_locator'
        tags:
            - { name: console.command }

    Oro\Bundle\InstallerBundle\Command\PlatformUpdateCommand:
        public: false
        class: Oro\Bundle\InstallerBundle\Command\PlatformUpdateCommand
        tags:
            - { name: console.command }

    Oro\Bundle\InstallerBundle\Command\RunScriptsCommand:
        public: false
        class: Oro\Bundle\InstallerBundle\Command\RunScriptsCommand
        tags:
            - { name: console.command }
