placeholders:
    placeholders:
        requirejs_config_extend:
            items:
                form_requirejs_config:
                    order: 100

    items:
        form_requirejs_config:
            template: OroFormBundle::requirejs.config.js.twig
            applicable: "@oro_layout.helper->isTemplateRequest()"
