services:
    Oro\Bundle\ImapBundle\Command\Cron\EmailSyncCommand:
        public: false
        class: Oro\Bundle\ImapBundle\Command\Cron\EmailSyncCommand
        arguments:
            - '@oro_featuretoggle.checker.feature_checker'
            - '@oro_imap.email_synchronizer'
        tags:
            - { name: console.command }

    Oro\Bundle\ImapBundle\Command\Cron\SendCredentialNotificationsCommand:
        public: false
        class: Oro\Bundle\ImapBundle\Command\Cron\SendCredentialNotificationsCommand
        tags:
            - { name: console.command }
