demostyle:
    inputs:
        - "bundles/bowerassets/font-awesome/css/font-awesome.css"
        - "bundles/npmassets/slick-carousel/slick/slick.scss"

        - "bundles/oroviewswitcher/view-switcher/scss/styles.scss"
    output: css/themes/oro/view-switcher.css
