services:
    oro_workflow.twig.extension.workflow:
        class: 'Oro\Bundle\WorkflowBundle\Twig\WorkflowExtension'
        public: false
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: twig.extension }
            - { name: container.service_subscriber }
