services:
    _defaults:
        public: false

    Oro\Bundle\EntityExtendBundle\Command\CacheCheckCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityExtendBundle\Command\CacheClearCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityExtendBundle\Command\CacheWarmupCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityExtendBundle\Command\MigrationUpdateConfigCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityExtendBundle\Command\RouterCacheClearCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityExtendBundle\Command\UpdateConfigCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityExtendBundle\Command\UpdateSchemaCommand:
        arguments:
            - '@doctrine'
            - '@oro_entity_config.provider.extend_entity_config_provider'
            - '@oro_entity_extend.enum_synchronizer'
        tags:
            - { name: console.command }
