services:
    oro_navigation.content_provider.menu.history_menu:
        class: Oro\Bundle\NavigationBundle\ContentProvider\MenuContentProvider
        arguments:
            - '@oro_menu.twig.extension'
            - "history"
            - "history"
        tags:
            - { name: oro_ui.content_provider }

    oro_navigation.content_provider.menu.mostviewed_menu:
        class: Oro\Bundle\NavigationBundle\ContentProvider\MenuContentProvider
        arguments:
            - '@oro_menu.twig.extension'
            - "mostviewed"
            - "mostviewed"
        tags:
            - { name: oro_ui.content_provider }

    oro_navigation.content_provider.menu.application_menu:
        class: Oro\Bundle\NavigationBundle\ContentProvider\MenuContentProvider
        arguments:
            - '@oro_menu.twig.extension'
            - "application_menu"
            - "mainMenu"
        tags:
            - { name: oro_ui.content_provider, enabled: false }

    oro_navigation.content_provider.title:
        class: Oro\Bundle\NavigationBundle\ContentProvider\TitleContentProvider
        arguments:
            - '@oro_navigation.title_service'
        tags:
            - { name: oro_ui.content_provider }

    oro_navigation.content_provider.title_short:
        class: Oro\Bundle\NavigationBundle\ContentProvider\TitleShortContentProvider
        arguments:
            - '@oro_navigation.title_service'
        tags:
            - { name: oro_ui.content_provider }

    oro_navigation.content_provider.title_serialized:
        class: Oro\Bundle\NavigationBundle\ContentProvider\TitleSerializedContentProvider
        arguments:
            - '@oro_navigation.title_service'
        tags:
            - { name: oro_ui.content_provider }

    oro_navigation.content_provider.navigation_elements:
        class: Oro\Bundle\NavigationBundle\ContentProvider\NavigationElementsContentProvider
        arguments:
            - '@oro_navigation.configuration.provider'
            - '@request_stack'
        tags:
            - { name: oro_ui.content_provider }
