services:
    _defaults:
        public: false

    Oro\Bundle\TranslationBundle\Command\OroLanguageUpdateCommand:
        arguments:
            - '@oro_translation.provider.external_translations'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationDumpCommand:
        public: false
        class: Oro\Bundle\TranslationBundle\Command\OroTranslationDumpCommand
        arguments:
            - '@oro_translation.js_dumper'
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationLoadCommand:
        arguments:
            - '@doctrine'
            - '@translator'
            - '@oro_translation.database_translation.persister'
            - '@oro_translation.provider.language'
            - '@oro_translation.database_translation.loader'
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationPackCommand:
        arguments:
            - '@Oro\Bundle\TranslationBundle\Provider\TranslationPackDumper'
            - '@oro_translation.service_provider'
            - '@oro_translation.packages_provider.translation'
            - '@Oro\Bundle\TranslationBundle\DependencyInjection\Compiler\TranslationAdaptersCollection'
            - '%kernel.project_dir%'
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationResetCommand:
        arguments:
            - '@translator.default'
            - '@doctrine.orm.entity_manager'
            - '@oro_translation.database_translation.loader'
            - '%kernel.default_locale%'
        tags:
            - { name: console.command }
