services:
    _defaults:
        public: false

    Oro\Bundle\TranslationBundle\Command\OroLanguageUpdateCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationDumpCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationLoadCommand:
        arguments:
            - '@doctrine'
            - '@translator'
            - '@oro_translation.database_translation.persister'
            - '@oro_translation.provider.language'
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationPackCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\TranslationBundle\Command\OroTranslationResetCommand:
        tags:
            - { name: console.command }
