services:
    oro_translation.strategy.provider.test:
        decorates: 'oro_translation.strategy.provider'
        parent: 'oro_translation.strategy.provider'
        public: true

    translator.default.stub:
        class: 'Oro\Bundle\TranslationBundle\Tests\Functional\Stub\TranslatorStub'
        decorates: 'translator.default'
        parent: 'translator.default'
        public: true
