knp_gaufrette:
    adapters:
        importexport:
            local:
                directory: '%kernel.project_dir%/var/import_export'
    filesystems:
        importexport:
            adapter:    importexport
            alias:      importexport_filesystem
