services:
    oro_help.help_link.cache:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_help_link' ] ]

    oro_help.model.help_link_provider:
        class: Oro\Bundle\HelpBundle\Model\HelpLinkProvider
        arguments:
            - '@request_stack'
            - '@oro_ui.controller_class_provider'
            - '@controller_name_converter'
            - '@oro_platform.composer.version_helper'
            - '@oro_help.help_link.cache'

    oro_help.twig.extension:
        class: Oro\Bundle\HelpBundle\Twig\HelpExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
