services:
    _defaults:
        public: false

    Oro\Bundle\IntegrationBundle\Command\CleanupCommand:
        arguments:
            - '@doctrine'
            - '@oro_entity.orm.native_query_executor_helper'
        tags:
            - { name: console.command }

    Oro\Bundle\IntegrationBundle\Command\SyncCommand:
        tags:
            - { name: console.command }
