parameters:
    oro_windows.entity.windows_state.class: Oro\Bundle\WindowsBundle\Entity\WindowsState

services:
    oro_windows.twig.extension:
        class: Oro\Bundle\WindowsBundle\Twig\WindowsExtension
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_windows.manager.windows_state_registry:
        class: Oro\Bundle\WindowsBundle\Manager\WindowsStateManagerRegistry
        arguments:
            - '@oro_windows.manager.windows_state'

    oro_windows.manager.windows_state.abstract:
        class: Oro\Bundle\WindowsBundle\Manager\WindowsStateManager
        abstract: true
        arguments:
            - '@security.token_storage'
            - '@oro_entity.doctrine_helper'
            - '@oro_windows.manager.windows_state_request'

    oro_windows.manager.windows_state:
        parent: oro_windows.manager.windows_state.abstract
        public: true
        arguments:
            - '%oro_windows.entity.windows_state.class%'
            - '%oro_user.entity.class%'

    oro_windows.manager.windows_state_request:
        class: Oro\Bundle\WindowsBundle\Manager\WindowsStateRequestManager
        arguments:
            - '@request_stack'
