services:
    Oro\Bundle\LayoutBundle\Command\DebugCommand:
        public: false
        class: Oro\Bundle\LayoutBundle\Command\DebugCommand
        arguments:
            - '@oro_layout.layout_manager'
            - '@oro_layout.method_phpdoc_extractor'
            - [] # block types
            - [] # data providers
        tags:
            - { name: console.command, command: 'oro:debug:layout' }
