services:
    oro_draft.event_listener_orm.draft_source_listener:
        class: Oro\Bundle\DraftBundle\EventListener\ORM\DraftSourceListener
        public: false
        arguments:
            - '%database_driver%'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: default }

    oro_draft.duplicator.extension_provider:
        class: Oro\Bundle\DraftBundle\Duplicator\ExtensionProvider
        arguments:
            - !tagged oro_draft.duplicator.extension

    oro_draft.expression.context_accessor:
        class: 'Oro\Component\ConfigExpression\ContextAccessor'

    oro_draft.publisher.publisher:
        class: Oro\Bundle\DraftBundle\Manager\Publisher
        arguments:
            - '@=service("oro_entity_config.config_manager").getProvider("draft")'
            - '@doctrine.orm.entity_manager'

    oro_draft.model.draft_manager:
        class: Oro\Bundle\DraftBundle\Manager\DraftManager
        arguments:
            - '@oro_draft.duplicator.extension_provider'
            - '@oro_action.expression.context_accessor'
            - '@oro_draft.publisher.publisher'
