services:
    _defaults:
        public: true

    oro_action.controller.ajax:
        class: 'Oro\Bundle\ActionBundle\Controller\AjaxController'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: 'container.service_subscriber' }

    Oro\Bundle\ActionBundle\Controller\AjaxController:
        alias: 'oro_action.controller.ajax'
