config:
  map:
    '*':
      'orodigitalasset/templates/digital-asset-choose-form/preview.html': 'orodigitalasset/templates/digital-asset-choose-form/preview.html'
      'orodigitalasset/templates/digital-asset-choose-form/choose.html': 'orodigitalasset/templates/digital-asset-choose-form/choose.html'
    paths:
      'orodigitalasset/js/app/views/digital-asset-choose-form-view': 'bundles/orodigitalasset/js/app/views/digital-asset-choose-form-view.js'
      'orodigitalasset/js/widget/digital-asset-dialog-widget': 'bundles/orodigitalasset/js/widget/digital-asset-dialog-widget.js'
