services:
    oro_digital_asset.provider.mime_types:
        class: Oro\Bundle\DigitalAssetBundle\Provider\MimeTypesProvider
        # Public because used in digital-asset-grid
        public: true
        arguments:
            - '@oro_config.manager'

    oro_digital_asset.form.type.digital_asset:
        class: Oro\Bundle\DigitalAssetBundle\Form\Type\DigitalAssetType
        arguments:
            - '@translator'
        tags:
            - { name: form.type }

    oro_digital_asset.acl.voter.digital_asset_deletion:
        class: Oro\Bundle\DigitalAssetBundle\Acl\Voter\DigitalAssetDeleteVoter
        tags:
            - { name: security.voter }

    oro_digital_asset.listener.source_changed_listener:
        class: Oro\Bundle\DigitalAssetBundle\EventListener\DigitalAssetSourceChangedListener
        arguments:
            - '@property_accessor'
        tags:
            - { name: doctrine.orm.entity_listener, entity: '%oro_attachment.file.entity.class%', event: postUpdate }

    oro_digital_asset.form.extension.use_digital_asset_type_extension:
        class: Oro\Bundle\DigitalAssetBundle\Form\Extension\UseDigitalAssetTypeExtension
        arguments:
            - '@oro_entity_config.config_manager'
        tags:
            - { name: form.type_extension }
