services:
    oro_digital_asset.provider.mime_types:
        class: Oro\Bundle\DigitalAssetBundle\Provider\MimeTypesProvider
        # Public because used in digital-asset-grid
        public: true
        arguments:
            - '@oro_config.manager'

    oro_digital_asset.form.type.digital_asset:
        class: Oro\Bundle\DigitalAssetBundle\Form\Type\DigitalAssetType
        arguments:
            - '@translator'
        tags:
            - { name: form.type }

    oro_digital_asset.acl.voter.digital_asset_deletion:
        class: Oro\Bundle\DigitalAssetBundle\Acl\Voter\DigitalAssetDeleteVoter
        tags:
            - { name: security.voter }
