services:
    Oro\Bundle\DigitalAssetBundle\Validator\Constraints\DigitalAssetSourceFileValidator:
        arguments:
            - !service
                class: Symfony\Component\Validator\Constraints\FileValidator
            - '@oro_config.manager'
            - '@oro_digital_asset.provider.mime_types'
        tags:
            - { name: validator.constraint_validator }

    Oro\Bundle\DigitalAssetBundle\Validator\Constraints\DigitalAssetSourceFileMimeTypeValidator:
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_attachment.tools.mime_type_checker'
            - '@router'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: validator.constraint_validator }
