services:
    _defaults:
        public: true

    Oro\Bundle\EmailBundle\Controller\AutoResponseRuleController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: 'container.service_subscriber' }

    Oro\Bundle\EmailBundle\Controller\Dashboard\DashboardController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: 'container.service_subscriber' }
