services:
    _defaults:
        public: false

    Oro\Bundle\EntityConfigBundle\Command\CacheClearCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityConfigBundle\Command\CacheWarmupCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityConfigBundle\Command\DebugCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\EntityConfigBundle\Command\UpdateCommand:
        arguments:
            - '@oro_entity_config.config_loader'
        tags:
            - { name: console.command }
