services:
    _defaults:
        public: true

    Oro\Bundle\SegmentBundle\Controller\SegmentController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_entity_config.provider.entity' }
