action_groups:
    oro_draft_create:
        parameters:
            source:
                type: object
            flush:
                type: boolean
                default: true
        actions:
            - '@draft_create':
                source: $.source
                target: $.target
            - '@tree':
                conditions:
                    '@equal': [true, $.flush]
                actions:
                    - '@flush_entity': $.target
                    - '@flash_message':
                        message: oro.draft.operations.create.success
                        type: 'success'
                    - '@draft_redirect':
                        source: $.target
                        route: $.routes[update]
    oro_draft_publish:
        parameters:
            source:
                type: object
        actions:
            - '@draft_publish':
                source: $.source
                target: $.target
            - '@remove_entity': $.source
            - '@flush_entity': $.target
            - '@flash_message':
                message: oro.draft.operations.publish.success
                type: 'success'
            - '@draft_redirect':
                source: $.target
                route: $.routes[view]

operations:
    CREATE_DRAFT:
        label: oro.draft.operations.create.label
        for_all_entities: true
        acl_resource: [[VIEW], $.data]
        groups:
            - view_navButtons
        button_options:
            icon: fa-files-o
            class: btn
        preconditions:
            '@and':
                - '@equal': [$.data.draftUuid, null]
                - '@equal': [$.data.draftSource, null]
                - '@equal': [$.data.draftProject, null]
                - '@instanceof': [$.data, Oro\Bundle\DraftBundle\Entity\DraftableInterface]
        actions:
            - '@run_action_group':
                  action_group: oro_draft_create
                  parameters_mapping:
                      source: $.data
                  results:
                      redirectUrl: $.redirectUrl

    PUBLISH_DRAFT:
        label: oro.draft.operations.publish.label
        button_options:
            icon: fa-files-o
            class: btn
        for_all_entities: true
        acl_resource: [[VIEW], $.data]
        groups:
            - view_navButtons
        preconditions:
            '@and':
                - '@not_equal': [$.data.draftUuid, null]
                - '@not_equal': [$.data.draftSource, null]
                - '@instanceof': [$.data, Oro\Bundle\DraftBundle\Entity\DraftableInterface]
        actions:
            - '@run_action_group':
                action_group: oro_draft_publish
                parameters_mapping:
                    source: $.data
                results:
                    redirectUrl: $.redirectUrl
